# Generated by Django 4.2.20 on 2025-04-18 11:04

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identification_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('publish_on_job_page', models.BooleanField(default=False)),
                ('job_page_publish_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('fb_social', models.URLField(blank=True, null=True)),
                ('insta_social', models.URLField(blank=True, null=True)),
                ('linkedin_social', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('post_with_logo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_jobs', models.DateTimeField()),
                ('job_type', models.CharField(choices=[('ვაკანსია', 'ვაკანსია'), ('ტრენინგი/განათლება', 'ტრენინგი/განათლება'), ('ტენდერი', 'ტენდერი'), ('სხვა', 'სხვა')], default='ვაკანსია', max_length=20)),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('company_page_small_job_description', models.TextField(blank=True, null=True)),
                ('has_salary', models.BooleanField(blank=True, default=False)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('salary_currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('GEL', 'Georgian Lari'), ('EUR', 'Euro')], max_length=3, null=True)),
                ('exact_cities', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.ManyToManyField(blank=True, related_name='jobs', to='jobs.jobcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
                ('job_time_types', models.ManyToManyField(related_name='jobs', to='jobs.jobtimetype')),
                ('locations', models.ManyToManyField(related_name='jobs', to='jobs.location')),
            ],
        ),
    ]
