# Generated by Django 4.2.20 on 2025-04-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='jobtimetype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
    ]
