# Generated by Django 4.2.20 on 2025-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcategory_slug_jobtimetype_slug_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_foreign_language',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
